name: Deploy static site to S3 via OIDC
on:
  push:
    branches: [main, dev]

permissions:
  id-token: write      # ★ allows OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1️⃣  Swap OIDC JWT for STS creds
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::509904898151:role/gh-oidc-deploy
          aws-region: us-west-1      # pick your region

      # 2️⃣  Prove creds work (great for first test)
      - run: aws sts get-caller-identity

      # 3️⃣  Real work
      - name: Sync site to S3
        run: |
          aws s3 sync ./public s3://my-site-bucket --delete
