# .github/workflows/deploy.yml
name: Deploy Take5 static site via OIDC

on:
  push:
    branches: [dev, main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  DEV_BUCKET:  take5-dev
  PROD_BUCKET: take5-prod

jobs:
  deploy:
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show injected role ARN (debug)
        run: echo "AWS_ROLE_ARN = ${{ secrets.AWS_ROLE_ARN }}"


      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}   # set per-environment
          aws-region:     ${{ env.AWS_REGION }}

      - name: Upload artefact
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            BUCKET="${{ env.PROD_BUCKET }}"
          else
            BUCKET="${{ env.DEV_BUCKET }}"
          fi
          aws s3 cp ./index.html "s3://${BUCKET}/"
